body:
  - attributes:
      value: |
        Some general tips:

        * is this really a problem?
        * is this a problem here?
    type: markdown
  - attributes:
      label: Initial checklist
      options:
        - label: I read the [support docs](https://mdxjs.com/community/support/)
          required: true
        - label: I read the [contributing guide](https://mdxjs.com/community/contribute/)
          required: true
        - label: I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/main/code-of-conduct.md)
          required: true
        - label: I searched [issues](https://github.com/search?q=user%3Amdx-js&type=issues) and [discussions](https://github.com/orgs/mdx-js/discussions) and couldn’t find anything (or linked relevant results below)
          required: true
    id: initial-checklist
    type: checkboxes
  - attributes:
      description: |
        Please describe the problem.

        Forget about the particular solution you have in mind.
        Solution time is later!

        What is missing? What are the use cases?
        Describe which use cases are important and which are nice to have.
        Convince the maintainers that there is a real problem.
      label: Problem
    id: problem
    type: textarea
    validations:
      required: true
  - attributes:
      description: |
        Are there existing solutions?
        Can these use cases be addressed already?
      label: Current solutions
    id: alternatives
    type: textarea
    validations:
      required: true
  - attributes:
      description: |
        What is a better solution?
        Why is that better than current solutions at addressing the use cases?
      label: Proposed solutions
    id: solution
    type: textarea
    validations:
      required: true
description: Suggest an idea
name: 🚀 Feature
